### ISSUE TITLE
Widget documentation beta launch checklist

### ISSUE THREAD

**Issue by odhiaaa** [inlivedev/inlive-website#107]
Documentation needed for beta launch checklist
- [x] Tutorials on how to create and manage a widget @GagahGK 
- [x] The concept of Real Time Widget API @bonnis 
- [x] Guide to subscribe to the SSE @bonnis 
- [x] Guide to publish message through the channel server (including sample message) @bonnis
