### ISSUE TITLE
Developer Checklist To Make Sure Developer Can Create Their Own App

### ISSUE THREAD

**Issue by addonrizky** [inlivedev/inlive-website#75]
1. Developer enter ke documentation via landing page, consider senior dev (seek for documentation completeness) and junior dev (seek for tutorial : ready). things to achieve for senior dev:

Must Have : 
- [x] overview of our API (protocol, data format, API auth, link to apidoc) 
- [ ] architecture overview (how our infrastructure works). Focus on flow of the stream.
- [x] #89

Good To Have :
- [ ] referenced library to be explored regarding livestreaming : e.g Pion, node-webrtc, etc. 
- [ ] FAQ 

2. API Doc improvement:
- [x] #87
- [x] #88
